"""initial schema

Revision ID: 0db50f46d11e
Revises:
Create Date: 2026-09-29 16:07:34.559941+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0db50f46d11e"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bot_texts",
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column("is_custom", sa.Boolean(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "button_styles",
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("label", sa.String(length=128), nullable=False),
        sa.Column("style", sa.String(length=16), nullable=True),
        sa.Column("icon_custom_emoji_id", sa.String(length=64), nullable=True),
        sa.Column("emoji_fallback", sa.String(length=16), nullable=True),
        sa.Column("group", sa.String(length=32), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("is_visible", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_index(op.f("ix_button_styles_created_at"), "button_styles", ["created_at"], unique=False)
    op.create_table(
        "card_accounts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("card_number", sa.String(length=32), nullable=False),
        sa.Column("holder_name", sa.String(length=128), nullable=False),
        sa.Column("bank_name", sa.String(length=64), nullable=True),
        sa.Column("iban", sa.String(length=34), nullable=True),
        sa.Column("instructions", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_card_accounts_created_at"), "card_accounts", ["created_at"], unique=False)
    op.create_index(op.f("ix_card_accounts_is_active"), "card_accounts", ["is_active"], unique=False)
    op.create_table(
        "channels",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("chat_id", sa.String(length=64), nullable=False),
        sa.Column("title", sa.String(length=128), nullable=False),
        sa.Column("invite_link", sa.String(length=255), nullable=True),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("auto_approve_joins", sa.Boolean(), nullable=False),
        sa.Column("show_in_menu", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("note", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_channels_created_at"), "channels", ["created_at"], unique=False)
    op.create_table(
        "discount_codes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column(
            "kind", sa.Enum("PERCENT", "AMOUNT", name="discountkind", native_enum=False, length=32), nullable=False
        ),
        sa.Column("value", sa.BigInteger(), nullable=False),
        sa.Column("max_discount_rial", sa.BigInteger(), nullable=True),
        sa.Column("min_amount_rial", sa.BigInteger(), nullable=False),
        sa.Column("max_uses", sa.Integer(), nullable=True),
        sa.Column("per_user_limit", sa.Integer(), nullable=False),
        sa.Column("used_count", sa.Integer(), nullable=False),
        sa.Column(
            "applies_to_plans",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("note", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_discount_codes_code"), "discount_codes", ["code"], unique=True)
    op.create_index(op.f("ix_discount_codes_created_at"), "discount_codes", ["created_at"], unique=False)
    op.create_table(
        "gift_codes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("value", sa.BigInteger(), nullable=False),
        sa.Column("max_uses", sa.Integer(), nullable=True),
        sa.Column("per_user_limit", sa.Integer(), nullable=False),
        sa.Column("used_count", sa.Integer(), nullable=False),
        sa.Column("min_amount_rial", sa.BigInteger(), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("note", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_gift_codes_code"), "gift_codes", ["code"], unique=True)
    op.create_index(op.f("ix_gift_codes_created_at"), "gift_codes", ["created_at"], unique=False)
    op.create_table(
        "guides",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=160), nullable=False),
        sa.Column("section", sa.String(length=24), nullable=False),
        sa.Column("platform", sa.String(length=24), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("media_file_id", sa.Text(), nullable=True),
        sa.Column("media_type", sa.String(length=16), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("views", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_guides_created_at"), "guides", ["created_at"], unique=False)
    op.create_index(op.f("ix_guides_is_active"), "guides", ["is_active"], unique=False)
    op.create_index(op.f("ix_guides_section"), "guides", ["section"], unique=False)
    op.create_table(
        "panels",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("base_url", sa.String(length=255), nullable=False),
        sa.Column("subscription_base_url", sa.String(length=255), nullable=True),
        sa.Column("api_token_encrypted", sa.Text(), nullable=False),
        sa.Column("webhook_secret_encrypted", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("max_services", sa.Integer(), nullable=True),
        sa.Column("capacity_note", sa.String(length=255), nullable=True),
        sa.Column("default_interface_id", sa.String(length=64), nullable=True),
        sa.Column("default_interface_name", sa.String(length=64), nullable=True),
        sa.Column(
            "health",
            sa.Enum("UNKNOWN", "ONLINE", "DEGRADED", "OFFLINE", name="panelhealth", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("health_message", sa.String(length=255), nullable=True),
        sa.Column("last_checked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("node_version", sa.String(length=64), nullable=True),
        sa.Column("node_id", sa.String(length=64), nullable=True),
        sa.Column("uptime_seconds", sa.BigInteger(), nullable=True),
        sa.Column("service_count", sa.Integer(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_panels_created_at"), "panels", ["created_at"], unique=False)
    op.create_index(op.f("ix_panels_is_active"), "panels", ["is_active"], unique=False)
    op.create_table(
        "plan_categories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("icon", sa.String(length=32), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_visible", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("banner_file_id", sa.Text(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["parent_id"], ["plan_categories.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("parent_id", "name", name="uq_category_sibling_name"),
    )
    op.create_index("ix_categories_parent_sort", "plan_categories", ["parent_id", "sort_order"], unique=False)
    op.create_index(op.f("ix_plan_categories_created_at"), "plan_categories", ["created_at"], unique=False)
    op.create_index(op.f("ix_plan_categories_is_active"), "plan_categories", ["is_active"], unique=False)
    op.create_index(op.f("ix_plan_categories_parent_id"), "plan_categories", ["parent_id"], unique=False)
    op.create_table(
        "settings",
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column(
            "value", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=True
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "staff",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("telegram_id", sa.BigInteger(), nullable=True),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column(
            "role", sa.Enum("OWNER", "ADMIN", "SUPPORT", name="staffrole", native_enum=False, length=32), nullable=False
        ),
        sa.Column("login", sa.String(length=64), nullable=True),
        sa.Column("password_hash", sa.String(length=255), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("receive_receipts", sa.Boolean(), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_staff_created_at"), "staff", ["created_at"], unique=False)
    op.create_index(op.f("ix_staff_login"), "staff", ["login"], unique=True)
    op.create_index(op.f("ix_staff_role"), "staff", ["role"], unique=False)
    op.create_index(op.f("ix_staff_telegram_id"), "staff", ["telegram_id"], unique=True)
    op.create_table(
        "system_events",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column(
            "level",
            sa.Enum("INFO", "WARNING", "ERROR", "CRITICAL", name="eventlevel", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("meta", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_system_events_created_at"), "system_events", ["created_at"], unique=False)
    op.create_index(op.f("ix_system_events_level"), "system_events", ["level"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("telegram_id", sa.BigInteger(), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=True),
        sa.Column("first_name", sa.String(length=128), nullable=True),
        sa.Column("last_name", sa.String(length=128), nullable=True),
        sa.Column("language_code", sa.String(length=16), nullable=True),
        sa.Column("is_blocked", sa.Boolean(), nullable=False),
        sa.Column("block_reason", sa.String(length=255), nullable=True),
        sa.Column("is_bot_blocked", sa.Boolean(), nullable=False),
        sa.Column("balance_rial", sa.BigInteger(), nullable=False),
        sa.Column("referral_code", sa.String(length=16), nullable=True),
        sa.Column("referred_by_id", sa.Integer(), nullable=True),
        sa.Column("referral_earnings_rial", sa.BigInteger(), nullable=False),
        sa.Column("test_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("test_count", sa.Integer(), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("meta", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["referred_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_created_at"), "users", ["created_at"], unique=False)
    op.create_index(op.f("ix_users_is_blocked"), "users", ["is_blocked"], unique=False)
    op.create_index(op.f("ix_users_last_seen_at"), "users", ["last_seen_at"], unique=False)
    op.create_index(op.f("ix_users_referral_code"), "users", ["referral_code"], unique=True)
    op.create_index(op.f("ix_users_telegram_id"), "users", ["telegram_id"], unique=True)
    op.create_table(
        "webhook_events",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("event_type", sa.String(length=48), nullable=False),
        sa.Column("node_id", sa.String(length=64), nullable=True),
        sa.Column(
            "payload", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=True
        ),
        sa.Column("received_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_webhook_events_event_type"), "webhook_events", ["event_type"], unique=False)
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("staff_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("actor_label", sa.String(length=128), nullable=True),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("entity", sa.String(length=32), nullable=True),
        sa.Column("entity_id", sa.String(length=64), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("meta", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=True),
        sa.Column("ip", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["staff_id"], ["staff.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_audit_created", "audit_logs", ["created_at"], unique=False)
    op.create_index(op.f("ix_audit_logs_action"), "audit_logs", ["action"], unique=False)
    op.create_index(op.f("ix_audit_logs_staff_id"), "audit_logs", ["staff_id"], unique=False)
    op.create_index(op.f("ix_audit_logs_user_id"), "audit_logs", ["user_id"], unique=False)
    op.create_table(
        "broadcasts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_by_staff_id", sa.Integer(), nullable=True),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("media_file_id", sa.Text(), nullable=True),
        sa.Column("media_type", sa.String(length=16), nullable=True),
        sa.Column(
            "buttons", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=True
        ),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT", "RUNNING", "DONE", "CANCELED", "FAILED", name="broadcaststatus", native_enum=False, length=32
            ),
            nullable=False,
        ),
        sa.Column("audience", sa.String(length=32), nullable=False),
        sa.Column("total", sa.Integer(), nullable=False),
        sa.Column("sent", sa.Integer(), nullable=False),
        sa.Column("failed", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["created_by_staff_id"], ["staff.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_broadcasts_created_at"), "broadcasts", ["created_at"], unique=False)
    op.create_index(op.f("ix_broadcasts_scheduled_at"), "broadcasts", ["scheduled_at"], unique=False)
    op.create_index(op.f("ix_broadcasts_status"), "broadcasts", ["status"], unique=False)
    op.create_table(
        "plans",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("panel_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("category", sa.String(length=64), nullable=True),
        sa.Column("category_id", sa.Integer(), nullable=True),
        sa.Column(
            "features", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=True
        ),
        sa.Column("is_featured", sa.Boolean(), nullable=False),
        sa.Column("traffic_gb", sa.Integer(), nullable=True),
        sa.Column("duration_days", sa.Integer(), nullable=True),
        sa.Column("device_limit", sa.Integer(), nullable=False),
        sa.Column("speed_limit_down_kbps", sa.Integer(), nullable=True),
        sa.Column("speed_limit_up_kbps", sa.Integer(), nullable=True),
        sa.Column("start_policy", sa.String(length=24), nullable=False),
        sa.Column("price_rial", sa.BigInteger(), nullable=False),
        sa.Column("old_price_rial", sa.BigInteger(), nullable=True),
        sa.Column("cost_rial", sa.BigInteger(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_test", sa.Boolean(), nullable=False),
        sa.Column("is_unlimited_stock", sa.Boolean(), nullable=False),
        sa.Column("stock", sa.Integer(), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("badge", sa.String(length=32), nullable=True),
        sa.Column("wg_plan_id", sa.String(length=64), nullable=True),
        sa.Column("interface_id", sa.String(length=64), nullable=True),
        sa.Column("username_template", sa.String(length=64), nullable=False),
        sa.Column("sales_count", sa.Integer(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["category_id"], ["plan_categories.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["panel_id"], ["panels.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_plans_category_id"), "plans", ["category_id"], unique=False)
    op.create_index(op.f("ix_plans_created_at"), "plans", ["created_at"], unique=False)
    op.create_index(op.f("ix_plans_is_active"), "plans", ["is_active"], unique=False)
    op.create_table(
        "tickets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ticket_code", sa.String(length=16), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("subject", sa.String(length=255), nullable=False),
        sa.Column(
            "status",
            sa.Enum("OPEN", "ANSWERED", "PENDING", "CLOSED", name="ticketstatus", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("assigned_staff_id", sa.Integer(), nullable=True),
        sa.Column("unread_for_staff", sa.Integer(), nullable=False),
        sa.Column("unread_for_user", sa.Integer(), nullable=False),
        sa.Column("last_message_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["assigned_staff_id"], ["staff.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tickets_created_at"), "tickets", ["created_at"], unique=False)
    op.create_index(op.f("ix_tickets_last_message_at"), "tickets", ["last_message_at"], unique=False)
    op.create_index(op.f("ix_tickets_status"), "tickets", ["status"], unique=False)
    op.create_index(op.f("ix_tickets_ticket_code"), "tickets", ["ticket_code"], unique=True)
    op.create_index(op.f("ix_tickets_user_id"), "tickets", ["user_id"], unique=False)
    op.create_table(
        "services",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("panel_id", sa.Integer(), nullable=False),
        sa.Column("plan_id", sa.Integer(), nullable=True),
        sa.Column("origin_order_id", sa.Integer(), nullable=True),
        sa.Column("wg_user_id", sa.String(length=64), nullable=False),
        sa.Column("wg_username", sa.String(length=64), nullable=False),
        sa.Column("subscription_encrypted", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "ACTIVE",
                "DISABLED",
                "EXPIRED",
                "TRAFFIC_EXCEEDED",
                "DELETED",
                name="servicestatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("remote_status", sa.String(length=32), nullable=True),
        sa.Column("disable_reason", sa.String(length=32), nullable=True),
        sa.Column("traffic_limit_bytes", sa.BigInteger(), nullable=True),
        sa.Column("traffic_used_bytes", sa.BigInteger(), nullable=False),
        sa.Column("device_limit", sa.Integer(), nullable=False),
        sa.Column("speed_limit_down_kbps", sa.Integer(), nullable=True),
        sa.Column("speed_limit_up_kbps", sa.Integer(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_activity_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_test", sa.Boolean(), nullable=False),
        sa.Column("auto_renew", sa.Boolean(), nullable=False),
        sa.Column("notified_3d", sa.Boolean(), nullable=False),
        sa.Column("notified_1d", sa.Boolean(), nullable=False),
        sa.Column("notified_expired", sa.Boolean(), nullable=False),
        sa.Column("notified_80pct", sa.Boolean(), nullable=False),
        sa.Column("notified_100pct", sa.Boolean(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("meta", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["origin_order_id"], ["orders.id"], name="fk_services_origin_order", ondelete="SET NULL", use_alter=True
        ),
        sa.ForeignKeyConstraint(["panel_id"], ["panels.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["plan_id"], ["plans.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_services_created_at"), "services", ["created_at"], unique=False)
    op.create_index(op.f("ix_services_expires_at"), "services", ["expires_at"], unique=False)
    op.create_index(op.f("ix_services_status"), "services", ["status"], unique=False)
    op.create_index(op.f("ix_services_user_id"), "services", ["user_id"], unique=False)
    op.create_index(op.f("ix_services_wg_user_id"), "services", ["wg_user_id"], unique=False)
    op.create_table(
        "ticket_messages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ticket_id", sa.Integer(), nullable=False),
        sa.Column(
            "sender", sa.Enum("USER", "STAFF", name="ticketsender", native_enum=False, length=32), nullable=False
        ),
        sa.Column("staff_id", sa.Integer(), nullable=True),
        sa.Column("text", sa.Text(), nullable=True),
        sa.Column("file_id", sa.Text(), nullable=True),
        sa.Column("file_type", sa.String(length=16), nullable=True),
        sa.Column("delivered", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["staff_id"], ["staff.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["ticket_id"], ["tickets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ticket_messages_created_at"), "ticket_messages", ["created_at"], unique=False)
    op.create_index(op.f("ix_ticket_messages_ticket_id"), "ticket_messages", ["ticket_id"], unique=False)
    op.create_table(
        "orders",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("order_code", sa.String(length=24), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("plan_id", sa.Integer(), nullable=True),
        sa.Column("panel_id", sa.Integer(), nullable=True),
        sa.Column("service_id", sa.Integer(), nullable=True),
        sa.Column(
            "kind",
            sa.Enum(
                "NEW", "RENEW", "EXTRA_TRAFFIC", "EXTRA_DEVICE", "TEST", name="orderkind", native_enum=False, length=32
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "PENDING_PAYMENT",
                "AWAITING_REVIEW",
                "PAID",
                "PROVISIONING",
                "COMPLETED",
                "FAILED",
                "CANCELED",
                "REFUNDED",
                "EXPIRED",
                name="orderstatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "payment_method",
            sa.Enum("CARD", "WALLET", "ADMIN", "GIFT", "REFERRAL", name="paymentmethod", native_enum=False, length=32),
            nullable=True,
        ),
        sa.Column("amount_rial", sa.BigInteger(), nullable=False),
        sa.Column("discount_rial", sa.BigInteger(), nullable=False),
        sa.Column("wallet_used_rial", sa.BigInteger(), nullable=False),
        sa.Column("payable_rial", sa.BigInteger(), nullable=False),
        sa.Column("discount_code_id", sa.Integer(), nullable=True),
        sa.Column("is_free", sa.Boolean(), nullable=False),
        sa.Column("plan_name", sa.String(length=128), nullable=False),
        sa.Column("traffic_gb", sa.Integer(), nullable=True),
        sa.Column("duration_days", sa.Integer(), nullable=True),
        sa.Column("device_limit", sa.Integer(), nullable=False),
        sa.Column("speed_limit_down_kbps", sa.Integer(), nullable=True),
        sa.Column("speed_limit_up_kbps", sa.Integer(), nullable=True),
        sa.Column("is_test", sa.Boolean(), nullable=False),
        sa.Column("wg_user_id", sa.String(length=64), nullable=True),
        sa.Column("wg_device_id", sa.String(length=64), nullable=True),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("failure_reason", sa.Text(), nullable=True),
        sa.Column("provisioned_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("payment_reference", sa.String(length=128), nullable=True),
        sa.Column("paid_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancel_reason", sa.String(length=255), nullable=True),
        sa.Column("payment_deadline", sa.DateTime(timezone=True), nullable=True),
        sa.Column("meta", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["discount_code_id"], ["discount_codes.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["panel_id"], ["panels.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["plan_id"], ["plans.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["service_id"], ["services.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key"),
    )
    op.create_index(op.f("ix_orders_created_at"), "orders", ["created_at"], unique=False)
    op.create_index(op.f("ix_orders_order_code"), "orders", ["order_code"], unique=True)
    op.create_index(op.f("ix_orders_status"), "orders", ["status"], unique=False)
    op.create_index("ix_orders_status_created", "orders", ["status", "created_at"], unique=False)
    op.create_index(op.f("ix_orders_user_id"), "orders", ["user_id"], unique=False)
    op.create_index("ix_orders_user_status", "orders", ["user_id", "status"], unique=False)
    op.create_index(op.f("ix_orders_wg_user_id"), "orders", ["wg_user_id"], unique=False)
    op.create_table(
        "service_devices",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("service_id", sa.Integer(), nullable=False),
        sa.Column("wg_device_id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("ipv4_address", sa.String(length=64), nullable=True),
        sa.Column("config_encrypted", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("rx_bytes", sa.BigInteger(), nullable=False),
        sa.Column("tx_bytes", sa.BigInteger(), nullable=False),
        sa.Column("last_handshake_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["service_id"], ["services.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("service_id", "wg_device_id", name="uq_service_device"),
    )
    op.create_index(op.f("ix_service_devices_created_at"), "service_devices", ["created_at"], unique=False)
    op.create_index(op.f("ix_service_devices_service_id"), "service_devices", ["service_id"], unique=False)
    op.create_table(
        "service_events",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("service_id", sa.Integer(), nullable=True),
        sa.Column("wg_user_id", sa.String(length=64), nullable=True),
        sa.Column("event_type", sa.String(length=48), nullable=False),
        sa.Column(
            "payload", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=True
        ),
        sa.Column("notified_user", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["service_id"], ["services.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_service_events_created_at"), "service_events", ["created_at"], unique=False)
    op.create_index(op.f("ix_service_events_event_type"), "service_events", ["event_type"], unique=False)
    op.create_index(op.f("ix_service_events_service_id"), "service_events", ["service_id"], unique=False)
    op.create_index(op.f("ix_service_events_wg_user_id"), "service_events", ["wg_user_id"], unique=False)
    op.create_table(
        "discount_redemptions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=True),
        sa.Column("amount_rial", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["code_id"], ["discount_codes.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["order_id"], ["orders.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code_id", "order_id", name="uq_redemption_order"),
    )
    op.create_index(op.f("ix_discount_redemptions_code_id"), "discount_redemptions", ["code_id"], unique=False)
    op.create_index(op.f("ix_discount_redemptions_created_at"), "discount_redemptions", ["created_at"], unique=False)
    op.create_index(op.f("ix_discount_redemptions_user_id"), "discount_redemptions", ["user_id"], unique=False)
    op.create_table(
        "gift_redemptions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("amount_rial", sa.BigInteger(), nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["code_id"], ["gift_codes.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["order_id"], ["orders.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_gift_redemptions_code_id"), "gift_redemptions", ["code_id"], unique=False)
    op.create_index(op.f("ix_gift_redemptions_user_id"), "gift_redemptions", ["user_id"], unique=False)
    op.create_table(
        "payments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=True),
        sa.Column(
            "kind",
            sa.Enum(
                "DEPOSIT",
                "PURCHASE",
                "REFUND",
                "ADJUSTMENT",
                "REFERRAL",
                "GIFT",
                name="paymentkind",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "method",
            sa.Enum("CARD", "WALLET", "ADMIN", "GIFT", "REFERRAL", name="paymentmethod", native_enum=False, length=32),
            nullable=True,
        ),
        sa.Column("amount_rial", sa.BigInteger(), nullable=False),
        sa.Column("balance_after_rial", sa.BigInteger(), nullable=False),
        sa.Column("reference", sa.String(length=128), nullable=True),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("created_by_staff_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["created_by_staff_id"], ["staff.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["order_id"], ["orders.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_payments_created_at"), "payments", ["created_at"], unique=False)
    op.create_index(op.f("ix_payments_kind"), "payments", ["kind"], unique=False)
    op.create_index("ix_payments_user_created", "payments", ["user_id", "created_at"], unique=False)
    op.create_index(op.f("ix_payments_user_id"), "payments", ["user_id"], unique=False)
    op.create_table(
        "receipts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=16), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=True),
        sa.Column("purpose", sa.String(length=16), nullable=False),
        sa.Column("amount_rial", sa.BigInteger(), nullable=False),
        sa.Column(
            "media",
            sa.Enum("PHOTO", "DOCUMENT", "TEXT", name="receiptmedia", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("file_id", sa.Text(), nullable=True),
        sa.Column("message_id", sa.BigInteger(), nullable=True),
        sa.Column("chat_id", sa.BigInteger(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("tracking_code", sa.String(length=64), nullable=True),
        sa.Column("payer_card_last4", sa.String(length=8), nullable=True),
        sa.Column("paid_at_text", sa.String(length=64), nullable=True),
        sa.Column(
            "status",
            sa.Enum("PENDING", "APPROVED", "REJECTED", "EXPIRED", name="receiptstatus", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("reviewed_by_staff_id", sa.Integer(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reject_reason", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["order_id"], ["orders.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["reviewed_by_staff_id"], ["staff.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_receipts_code"), "receipts", ["code"], unique=True)
    op.create_index(op.f("ix_receipts_created_at"), "receipts", ["created_at"], unique=False)
    op.create_index(op.f("ix_receipts_status"), "receipts", ["status"], unique=False)
    op.create_index("ix_receipts_status_created", "receipts", ["status", "created_at"], unique=False)
    op.create_index(op.f("ix_receipts_user_id"), "receipts", ["user_id"], unique=False)
    op.create_table(
        "receipt_messages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("receipt_id", sa.Integer(), nullable=False),
        sa.Column("staff_id", sa.Integer(), nullable=True),
        sa.Column("chat_id", sa.BigInteger(), nullable=False),
        sa.Column("message_id", sa.BigInteger(), nullable=False),
        sa.Column("is_media", sa.Boolean(), nullable=False),
        sa.Column("edited", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["receipt_id"], ["receipts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["staff_id"], ["staff.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_receipt_messages_receipt_id"), "receipt_messages", ["receipt_id"], unique=False)
    # ### end Alembic commands ###
    # `orders` <-> `services` is a reference cycle, so Alembic emits this
    # constraint separately (`use_alter=True` on the model).  Autogenerate
    # cannot order it, hence the explicit statement.
    op.create_foreign_key(
        "fk_services_origin_order",
        "services",
        "orders",
        ["origin_order_id"],
        ["id"],
        ondelete="SET NULL",
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_receipt_messages_receipt_id"), table_name="receipt_messages")
    op.drop_table("receipt_messages")
    op.drop_index(op.f("ix_receipts_user_id"), table_name="receipts")
    op.drop_index("ix_receipts_status_created", table_name="receipts")
    op.drop_index(op.f("ix_receipts_status"), table_name="receipts")
    op.drop_index(op.f("ix_receipts_created_at"), table_name="receipts")
    op.drop_index(op.f("ix_receipts_code"), table_name="receipts")
    op.drop_table("receipts")
    op.drop_index(op.f("ix_payments_user_id"), table_name="payments")
    op.drop_index("ix_payments_user_created", table_name="payments")
    op.drop_index(op.f("ix_payments_kind"), table_name="payments")
    op.drop_index(op.f("ix_payments_created_at"), table_name="payments")
    op.drop_table("payments")
    op.drop_index(op.f("ix_gift_redemptions_user_id"), table_name="gift_redemptions")
    op.drop_index(op.f("ix_gift_redemptions_code_id"), table_name="gift_redemptions")
    op.drop_table("gift_redemptions")
    op.drop_index(op.f("ix_discount_redemptions_user_id"), table_name="discount_redemptions")
    op.drop_index(op.f("ix_discount_redemptions_created_at"), table_name="discount_redemptions")
    op.drop_index(op.f("ix_discount_redemptions_code_id"), table_name="discount_redemptions")
    op.drop_table("discount_redemptions")
    op.drop_index(op.f("ix_service_events_wg_user_id"), table_name="service_events")
    op.drop_index(op.f("ix_service_events_service_id"), table_name="service_events")
    op.drop_index(op.f("ix_service_events_event_type"), table_name="service_events")
    op.drop_index(op.f("ix_service_events_created_at"), table_name="service_events")
    op.drop_table("service_events")
    op.drop_index(op.f("ix_service_devices_service_id"), table_name="service_devices")
    op.drop_index(op.f("ix_service_devices_created_at"), table_name="service_devices")
    op.drop_table("service_devices")
    op.drop_index(op.f("ix_orders_wg_user_id"), table_name="orders")
    op.drop_index("ix_orders_user_status", table_name="orders")
    op.drop_index(op.f("ix_orders_user_id"), table_name="orders")
    op.drop_index("ix_orders_status_created", table_name="orders")
    op.drop_index(op.f("ix_orders_status"), table_name="orders")
    op.drop_index(op.f("ix_orders_order_code"), table_name="orders")
    op.drop_index(op.f("ix_orders_created_at"), table_name="orders")
    op.drop_table("orders")
    op.drop_index(op.f("ix_ticket_messages_ticket_id"), table_name="ticket_messages")
    op.drop_index(op.f("ix_ticket_messages_created_at"), table_name="ticket_messages")
    op.drop_table("ticket_messages")
    op.drop_index(op.f("ix_services_wg_user_id"), table_name="services")
    op.drop_index(op.f("ix_services_user_id"), table_name="services")
    op.drop_index(op.f("ix_services_status"), table_name="services")
    op.drop_index(op.f("ix_services_expires_at"), table_name="services")
    op.drop_index(op.f("ix_services_created_at"), table_name="services")
    op.drop_table("services")
    op.drop_index(op.f("ix_tickets_user_id"), table_name="tickets")
    op.drop_index(op.f("ix_tickets_ticket_code"), table_name="tickets")
    op.drop_index(op.f("ix_tickets_status"), table_name="tickets")
    op.drop_index(op.f("ix_tickets_last_message_at"), table_name="tickets")
    op.drop_index(op.f("ix_tickets_created_at"), table_name="tickets")
    op.drop_table("tickets")
    op.drop_index(op.f("ix_plans_is_active"), table_name="plans")
    op.drop_index(op.f("ix_plans_created_at"), table_name="plans")
    op.drop_index(op.f("ix_plans_category_id"), table_name="plans")
    op.drop_table("plans")
    op.drop_index(op.f("ix_broadcasts_status"), table_name="broadcasts")
    op.drop_index(op.f("ix_broadcasts_scheduled_at"), table_name="broadcasts")
    op.drop_index(op.f("ix_broadcasts_created_at"), table_name="broadcasts")
    op.drop_table("broadcasts")
    op.drop_index(op.f("ix_audit_logs_user_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_staff_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_action"), table_name="audit_logs")
    op.drop_index("ix_audit_created", table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_index(op.f("ix_webhook_events_event_type"), table_name="webhook_events")
    op.drop_table("webhook_events")
    op.drop_index(op.f("ix_users_telegram_id"), table_name="users")
    op.drop_index(op.f("ix_users_referral_code"), table_name="users")
    op.drop_index(op.f("ix_users_last_seen_at"), table_name="users")
    op.drop_index(op.f("ix_users_is_blocked"), table_name="users")
    op.drop_index(op.f("ix_users_created_at"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_system_events_level"), table_name="system_events")
    op.drop_index(op.f("ix_system_events_created_at"), table_name="system_events")
    op.drop_table("system_events")
    op.drop_index(op.f("ix_staff_telegram_id"), table_name="staff")
    op.drop_index(op.f("ix_staff_role"), table_name="staff")
    op.drop_index(op.f("ix_staff_login"), table_name="staff")
    op.drop_index(op.f("ix_staff_created_at"), table_name="staff")
    op.drop_table("staff")
    op.drop_table("settings")
    op.drop_index(op.f("ix_plan_categories_parent_id"), table_name="plan_categories")
    op.drop_index(op.f("ix_plan_categories_is_active"), table_name="plan_categories")
    op.drop_index(op.f("ix_plan_categories_created_at"), table_name="plan_categories")
    op.drop_index("ix_categories_parent_sort", table_name="plan_categories")
    op.drop_table("plan_categories")
    op.drop_index(op.f("ix_panels_is_active"), table_name="panels")
    op.drop_index(op.f("ix_panels_created_at"), table_name="panels")
    op.drop_table("panels")
    op.drop_index(op.f("ix_guides_section"), table_name="guides")
    op.drop_index(op.f("ix_guides_is_active"), table_name="guides")
    op.drop_index(op.f("ix_guides_created_at"), table_name="guides")
    op.drop_table("guides")
    op.drop_index(op.f("ix_gift_codes_created_at"), table_name="gift_codes")
    op.drop_index(op.f("ix_gift_codes_code"), table_name="gift_codes")
    op.drop_table("gift_codes")
    op.drop_index(op.f("ix_discount_codes_created_at"), table_name="discount_codes")
    op.drop_index(op.f("ix_discount_codes_code"), table_name="discount_codes")
    op.drop_table("discount_codes")
    op.drop_index(op.f("ix_channels_created_at"), table_name="channels")
    op.drop_table("channels")
    op.drop_index(op.f("ix_card_accounts_is_active"), table_name="card_accounts")
    op.drop_index(op.f("ix_card_accounts_created_at"), table_name="card_accounts")
    op.drop_table("card_accounts")
    op.drop_index(op.f("ix_button_styles_created_at"), table_name="button_styles")
    op.drop_table("button_styles")
    op.drop_table("bot_texts")
    # ### end Alembic commands ###
    op.drop_constraint("fk_services_origin_order", "services", type_="foreignkey")
